@echo off
echo Iniciando contenedor MySQL...
docker-compose up -d

echo Esperando que MySQL esté listo...
timeout /t 30

echo Instalando dependencias...
npm install

echo Iniciando servidor...
npm start